name: Prettier CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    prettier:
        name: Run Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3

            - name: Install dependencies
              run: npm install

            - name: Run Prettier
              run: npm run format:check
